dist: xenial
language: python
python:
- '3.5'
- '3.6'
- '3.7'
install: pip install 'tox-travis ~= 0.12.0'
script: tox
deploy:
  provider: pypi
  user: dmtucker
  password:
    secure: kES9U8TtGRGEUR5PDLi+TOPaQ9zXcbXVE/NRT1ZQnpc/oDXvDb6+HY/8RR/WUbeJDFnf/EQm3EQCNO/cz79S4nVzhMgf6JMuLBmL2Z7bpGnN0JkrmlukWAO6VIgHe8EdYtzKdd+mB+NWwaAi+sDJFBdSrcZqXgVciaeLCEqWwq+5IByfIFxjEwUFz9fzsm7XPmTN4KolsUbCkimOKCHWIIl9/xuX6nZrzvWqiDrk4cHEEA+dRcZROLMk2nTODRF2pvhjTql3LkEpwxVLn9NHzQk4VMxunIGLITjzjTO1gMjBcWpXHPDufw3K2AfxONt2Nk0jO5hWVEzWXXww4cqnQ9I8nZJxMECVJTQlxDW2chwcSFKXlat0RsIxsCFVussEV1Nk6Fhj8Yhv72kV2g91NGtzmTstYkAv753ZU/3o6bTYXJCi+LcjSUi2wcUkPnp53jU1Gs94XWmRaIay/epNb3Fdms9jjWCo9n0ZN6Sd8HJwMjl5Fn6+rQVcECzFyG6gqx5ijoAFhfzNWE95qIJr/frpvkCGZp6yZmD+x72eBtv2FL4ZTY5odtxQCkDjNakvaIrwFIMCWhwyMY0ps5/QwW9rueX2xbmsFMt42gneGGATCOmgxqM88eqh63AI0JiR5b0+kxM49knTKAmfxmPRrmhBWG/yJjQIe+Wa0+WJsSY=
  on:
    repo: dmtucker/keysmith
    tags: true
    python: '3.5'
