language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
branches:
  only:
    - master
before_install:
  - pip install --upgrade pip
  - pip install pep8 pylint
install:
  - python setup.py sdist
  - pip install ./dist/*
script:
  - keysmith --help
  - pep8 keysmith setup.py
  - pylint keysmith setup.py
